# This is Part 2
Here we provide our own data

#### Imports:

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

### Reading df

In [44]:

df = pd.read_csv('ASE_info.csv')
df.index = df['Gene']
df

C:\Users\wmata\AppData\Local\Temp\ipykernel_21288\907357578.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('ASE_info.csv')

,Gene,Chromosome,Start(hg38),End(hg38),Start(hg19),End(hg19),Strand,ID(ENTREZ),Gene type,ID(Ensemble),...,Pancreatic_progenitor_(PP)_gene_ase_type,iPSCs_gene_ase_type,CNCCs_gene_ase_type,Cortical_organoids_d50_gene_ase_type,Cortical_organoids_d100_gene_ase_type,Cortical_organoids_d200_gene_ase_type,Endothelial_not_treated_gene_ase_type,Endothelial_TNF_gene_ase_type,Endothelial_Spin_gene_ase_type,ASE_count
Gene,,,,,,,,,,,,,,,,,,,,,
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,else,else,else,else,else,else,else,else,else,0
3.8-1.2,3.8-1.2,chr6,29995957.0,29996415.0,29963734.0,29964192.0,-,353007.0,pseudogene,NaN,...,else,else,else,else,else,else,else,else,else,0
3.8-1.4,3.8-1.4,chr6,29865915.0,29867087.0,29833692.0,29834864.0,-,353009.0,pseudogene,NaN,...,else,else,else,else,else,else,else,else,else,0
3.8-1.5,3.8-1.5,chr6,29765116.0,29766296.0,29732893.0,29734073.0,-,353010.0,pseudogene,NaN,...,else,else,else,else,else,else,else,else,else,0
5-HT3C2,5-HT3C2,chr3,184083172.0,184084219.0,183800960.0,183802007.0,+,389180.0,pseudogene,NaN,...,else,else,else,else,else,else,else,else,else,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11B,ZYG11B,chr1,52726454.0,52827342.0,53192126.0,53293014.0,+,79699.0,protein_coding,ENSG00000162378,...,ASE,ASE,nonASE,ASE,nonASE,nonASE,nonASE,nonASE,ASE,6
ZYX,ZYX,chr7,143381227.0,143391111.0,143078320.0,143088204.0,+,7791.0,protein_coding,ENSG00000159840,...,ASE,nonASE,nonASE,else,else,else,nonASE,nonASE,ASE,4
ZZEF1,ZZEF1,chr17,4004445.0,4143020.0,3907739.0,4046314.0,-,23140.0,protein_coding,ENSG00000074755,...,nonASE,ASE,nonASE,ASE,ASE,nonASE,nonASE,nonASE,nonASE,4
ZZZ3,ZZZ3,chr1,77561526.0,77683440.0,78027211.0,78149125.0,-,26009.0,protein_coding,ENSG00000036549,...,nonASE,nonASE,nonASE,nonASE,nonASE,nonASE,else,else,else,0
bA395L14.12,bA395L14.12,chr2,113657873.0,113658892.0,114415450.0,114416469.0,+,150478.0,pseudogene,NaN,...,else,else,else,else,else,else,else,else,else,0

### Cleaning DF

In [50]:
colums_to_drop = [col for col in df.columns if not re.search(r"TPM", col) or re.search(r"total", col)]
cleaned_df = df.drop(colums_to_drop, axis=1)
cleaned_df = cleaned_df.dropna(how='all', axis=0)
cleaned_df.shape

(20232, 84)

In [51]:
cleaned_df

,0_Fibroblast_TPM_human_allele,0_Fibroblast_TPM_chimp_allele,1_Fibroblast_TPM_human_allele,1_Fibroblast_TPM_chimp_allele,2_Mesenchyme_TPM_human_allele,2_Mesenchyme_TPM_chimp_allele,3_Fibroblast_TPM_human_allele,3_Fibroblast_TPM_chimp_allele,4_Prechondral_Mesenchyme_TPM_human_allele,4_Prechondral_Mesenchyme_TPM_chimp_allele,...,Cortical_organoids_d100_TPM_human_allele,Cortical_organoids_d100_TPM_chimp_allele,Cortical_organoids_d200_TPM_human_allele,Cortical_organoids_d200_TPM_chimp_allele,Endothelial_not_treated_TPM_human_allele,Endothelial_not_treated_TPM_chimp_allele,Endothelial_TNF_TPM_human_allele,Endothelial_TNF_TPM_chimp_allele,Endothelial_Spin_TPM_human_allele,Endothelial_Spin_TPM_chimp_allele
Gene,,,,,,,,,,,,,,,,,,,,,
A1BG,193.347870,141.440287,166.911330,62.685535,132.337764,40.772807,126.276959,29.246787,157.354893,18.003762,...,34.887706,12.352806,41.077640,22.500210,7.220118,0.713251,8.582152,1.135609,5.452845,0.780473
A1BG-AS1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.965017,1.946220,16.704872,2.488842,12.947885,1.558142
A1CF,0.051905,0.009890,0.011475,0.000000,0.042581,0.023973,0.000000,0.047726,0.040118,0.000000,...,0.010909,0.005385,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
A2M,2.729125,2.588288,3.595626,1.998305,14.448218,4.894162,31.190926,21.260811,9.820436,9.398465,...,87.921369,99.676360,200.655382,159.191454,163.385666,5.734534,87.252854,1.939122,141.790383,4.688861
A2M-AS1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.756730,0.970648,5.110261,0.421014,6.062472,0.851569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A,0.034145,0.000000,0.170165,0.037804,0.254452,0.000000,0.000000,0.322416,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZYG11B,24.047739,20.940850,25.671589,25.426115,20.956331,16.697681,34.848849,33.630274,21.264500,18.675445,...,49.041703,57.075874,43.118524,47.857169,30.914909,40.301353,19.504557,26.232124,24.594063,34.947615
ZYX,29.843882,30.389773,57.156730,57.120823,28.417939,39.430222,76.255330,62.050299,39.296403,38.677305,...,NaN,NaN,NaN,NaN,632.649129,607.930365,626.751283,621.687010,643.335300,608.736660
ZZEF1,2.205184,2.738612,2.033980,2.578784,1.663033,2.400751,2.871745,3.504902,1.753758,3.129467,...,38.890712,45.134012,40.074678,44.132121,34.032547,35.065151,31.788273,31.185317,35.702962,36.578428
ZZZ3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.112105,21.387271,20.182017,18.313944,NaN,NaN,NaN,NaN,NaN,NaN